  services:
    postgresql-service:
        image: postgres:10.5
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ../medai.sql:/docker-entrypoint-initdb.d/media.sql
          - ../auth-db/authdb_postgres.sql:/docker-entrypoint-initdb.d/authdb_postgres.sql
  